server:
  port: 8081

# Products service routes
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: productos-app
          uri: http://localhost:8080
          predicates:
            - Path=/api/productos/**


# Eureka client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}